version: "3.8"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.0
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
