apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inference
  namespace: mlops-factory
spec:
  selector:
    matchLabels:
      app: inference
  namespaceSelector:
    matchNames: ["mlops-factory"]
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
