name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps (lightweight)
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements-base.txt pytest flake8
    - name: Lint
      run: flake8 app tests
    - name: Tests
      run: pytest -q
